### ISSUE TITLE
change FSK-Lab feature to version 2.0.0

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#150] opened 2020-09-30 12:10 UTC
FSK-Lab for release candidate 2.0.0 is still using the 1.9.0 version number. Rename the version in the feature and reupload FSK-Lab to update site [2.0.0-rc1](https://bintray.com/fsk/2.0.0-rc1)

**Comment by miguelalba** [comment] 2020-10-01 11:33
The only way to test it I can think of is to check the installed software at KNIME's tab. @mfilter and @llavall, should we assign this to someone or can we close?

![image.png](https://images.zenhubusercontent.com/5d5bbc044c31c94967279dce/74caf4a2-f0fa-46ed-b6ec-85ae2fd97f23)

**Comment by mfilter** [comment] 2020-10-01 11:51
I tried to install from the development update site after having the last RC (28.09.) installed. The installation from the development update site can not be executed with this error message: 
"Cannot complete the install because of a conflicting dependency.
  Software being installed: BfR FSK-Lab 2.0.0.202010011001 (de.bund.bfr.knime.fsklab.feature.feature.group 2.0.0.202010011001)
  Software currently installed: BfR legacy FSK-Lab 1.0.0.202009281618 (de.bund.bfr.knime.fsklab.legacy.feature.feature.group 1.0.0.202009281618)
  Only one of the following can be installed at once: 
    JS libs 1.0.0.202010011001 (de.bund.bfr.knime.js 1.0.0.202010011001)
    JS libs 1.0.0.202009281618 (de.bund.bfr.knime.js 1.0.0.202009281618)
  Cannot satisfy dependency:
    From: BfR FSK-Lab 2.0.0.202010011001 (de.bund.bfr.knime.fsklab.feature.feature.group 2.0.0.202010011001)
    To: de.bund.bfr.knime.js [1.0.0.202010011001]
  Cannot satisfy dependency:
    From: BfR legacy FSK-Lab 1.0.0.202009281618 (de.bund.bfr.knime.fsklab.legacy.feature.feature.group 1.0.0.202009281618)
    To: de.bund.bfr.knime.js [1.0.0.202009281618]"

**Comment by llavall** [comment] 2020-10-01 14:58
for me the FSK legacy nodes are shown as version 0.0.1.202010011001 in the development version coming from 2.0.0 rc-1 shown as 1.9.0  I think


![Screen Shot 2020-10-01 at 16 55 14](https://user-images.githubusercontent.com/25248947/94825946-0c258600-0407-11eb-8f65-8e1ddb5f792b.png)


![Screen Shot 2020-10-01 at 16 57 09](https://user-images.githubusercontent.com/25248947/94826078-3bd48e00-0407-11eb-8d41-a9e220fb57d6.png)

Should it be this way?

**Comment by miguelalba** [comment] 2020-10-01 17:11
Thanks for the feedback. I installed from 2.0.0-rc1 and updated to development and got this:
![image](https://user-images.githubusercontent.com/19906968/94840830-5dd70c00-0419-11eb-8466-747edc9ee872.png)

The problem is that the legacy nodes feature are now gone and to be uninstalled. PMM-Lab and FSK-Lab can update. I could update by checking *Install different versions ...* and *Update items already installed*. My original error is:
```
Your original request has been modified.
  "PMM Nodes" is already installed, so an update will be performed instead.
  "BfR FSK-Lab" is already installed, so an update will be performed instead.
Cannot complete the install because of a conflicting dependency.
  Software being installed: BfR FSK-Lab 2.0.0.202010011001 (de.bund.bfr.knime.fsklab.feature.feature.group 2.0.0.202010011001)
  Software currently installed: BfR legacy FSK-Lab 1.0.0.202009281618 (de.bund.bfr.knime.fsklab.legacy.feature.feature.group 1.0.0.202009281618)
  Only one of the following can be installed at once: 
    FSK-Lab preferences 1.0.0.202010011001 (de.bund.bfr.knime.fsklab.preferences 1.0.0.202010011001)
    FSK-Lab preferences 1.0.0.202009281618 (de.bund.bfr.knime.fsklab.preferences 1.0.0.202009281618)
  Cannot satisfy dependency:
    From: BfR FSK-Lab 2.0.0.202010011001 (de.bund.bfr.knime.fsklab.feature.feature.group 2.0.0.202010011001)
    To: de.bund.bfr.knime.fsklab.preferences [1.0.0.202010011001]
  Cannot satisfy dependency:
    From: BfR legacy FSK-Lab 1.0.0.202009281618 (de.bund.bfr.knime.fsklab.legacy.feature.feature.group 1.0.0.202009281618)
    To: de.bund.bfr.knime.fsklab.preferences [1.0.0.202009281618]
```

**Comment by mfilter** [comment] 2020-10-13 12:48
If possible I would prefer to have the first 2.0 release installable without issues from ICPMF. There the question back @miguelalba : how much effort is it to provide the old BfR legacy FSK-Lab feature back with the new RC? If this creates much addtional work I will create an independent ticket for that so that we can close this one.

**Closed** 2020-10-13 13:58 UTC
